version: '3.8'

services:
  email-classifier-api:
    build: .
    container_name: email-classifier-api
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - PORT=8000
    volumes:
      # Optional: Mount model directory for external model updates
      # - ./models:/app/models:ro
      # Optional: Mount logs directory
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G
    networks:
      - email-classifier-network

networks:
  email-classifier-network:
    driver: bridge 